language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://mnaeem.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "qsZgDF1s/2/G5eHdQjgH0sA+2PcsMGvQ0/fF5P9CeQoCnUwNyCQSBSoW0qL23RmhXFj+lnbuYUuE4rBWbzmTW3TO2NVTtYrOLwep28kt8+a92RuHcUJ4qiTI9/6uXZedR9GkOh8C9GPB80ogZJfya/EJ5ZyXJoArgaykrW0wBwsvPrIzLQNIfrJaTd6r/BfRaOgD5ao/ifm7Klj9AqH728ToVdvTyxDrivZvVIe7ZeoxTq0zlvBrRSbvAi9CiY7OaDwO0Z5V4AGapgr+KwPdqSjrDtwCniEqGuMRjCrl1Qodf3ToRpbh+/BX0/WlPKeX7yc1welMVCdBCDUR5be+w9YdbUlT6bbepBTMnOf3/i+5G4zzhbSZoleGmxYE6zgVlFLx8FDE57OXby23LeFt17DXw1KbIwYBy5jYzn4+UNk+ViH3fQZY3jF189fdkeyFGUTcyPlod1eOfwZvvAL7UGpsLl1pTzFhnFyKByIuGr58UTjEvE1pZ+6kI+hiHw//hOXIZMN29oRDftB0RBHuyOV+VIvDQUiBNYR9F9cSF3QS8VHWeRjUe55wwY+bYwmKQgVIQm2AUcHoq7Qy8lu1nT5tKlKOjXG1O89X8CkiBdkYY7xGWajNCSVYXbJsaQVjS4s8TJfCVuwmZyLtE3yeuiHnEMhmqHea2nHUXTyYQIY="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
